bootstrap  v3 to v5
FreeCodeCamp-Chengdu/fcc.chengdu pull request #27
Opened 2024-10-12 15:34 UTC by luojiyin1987

2024-10-13 15:47 UTC, luojiyin1987 commented
![image](https://github.com/user-attachments/assets/c2becf80-f551-4c04-a790-3d160698b723)
是不是有些错位？  @TechQuery 

我也移除了  Bootstrap ,  发现对样式没影响。

2024-10-14 10:36 UTC, TechQuery requested changes

2024-10-14 10:36 UTC, TechQuery commented on .husky/pre-push
> +rm -rf .parcel-cache && npm run build
`build` 命令里有清缓存：https://github.com/FreeCodeCamp-Chengdu/fcc.chengdu/blob/3b2f777cbf5e4f82fae58ab3a368fe756b7a1b1e/package.json#L18-L21

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Events/index.tsx
> +import React from 'react';
```suggestion
```
React 17+ 没必要了

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Events/index.tsx
>      }
```suggestion
const items = list.map(({ type, title, date, describe, imageList: [{ url = '' } = {}] }) => ({
    title: date,
    cardTitle: `${type} - ${title}`,
    cardSubtitle: describe,
    cardDetailedText: describe,
    media: { type: 'IMAGE', source: { url } }
```

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Events/index.tsx
> +                <div className="col-md-12">
```suggestion
import { Container, Row, Col } from 'react-bootstrap';

export const Events: FC = () => (
        <Container>
            <Row>
                <Col md={12}>
```

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Events/index.tsx
> +                        }}
没有自定义样式的话，这个配置就没必要了。

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +import 'swiper/css/autoplay';
用 CDN 在 `index.html` 引入。

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +    }, []);
用类组件的 `createRef()`、`componentDidMount()`、`componentWillUnmount()` 写。

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +        }
```suggestion
            document.querySelector<HTMLElement>('.content-events');

        if (contentEvents)
            contentEvents.style.marginRight = `${(panelWidth - bodyWidth) / 2}px`;
```

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +                        >
```suggestion
                        <Swiper
                            className="swiper-container"
                            modules={[Navigation, Autoplay]}
                            grabCursor
                            slidesPerView={3}
                            centeredSlides={false}
                            slidesPerGroup={1}
                            spaceBetween={65}
                            loop
                            autoplay={{
                                delay: 3000,
                                disableOnInteraction: false
                            }}
                            navigation={{
                                nextEl: '#swiper-button-next',
                                prevEl: '#swiper-button-prev'
                            }}
                        >
```

2024-10-14 10:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +                                    </div>
```suggestion
                                        <img src={url + ''} alt={title} />
                                        <p className="text-white">
                                            {title}
                                        </p>
```
1. 应该不需要多套一层 `<div />` 了。
2. 样式尽量用工具类：https://getbootstrap.com/docs/5.3/utilities/colors/

2024-10-14 10:36 UTC, TechQuery commented on public/index.html
>          />
```suggestion
        <link
            rel="stylesheet"
            href="//unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        />
```

2024-10-14 10:36 UTC, TechQuery commented on public/index.html
> +        <script src="//unpkg.com/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script> -->
```suggestion
```
React Bootstrap 的 JavaScript 逻辑是内置

2024-10-14 10:41 UTC, TechQuery commented
> ![image](https://private-user-images.githubusercontent.com/6524977/376048721-c2becf80-f551-4c04-a790-3d160698b723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDI2NDksIm5iZiI6MTcyODkwMjM0OSwicGF0aCI6Ii82NTI0OTc3LzM3NjA0ODcyMS1jMmJlY2Y4MC1mNTUxLTRjMDQtYTc5MC0zZDE2MDY5OGI3MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTAzOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNmYmExNWFjZWQ5NTBlMDYwYTVhMDlhMjljZDgyYTgyZDQ1ODJlOTJiMWMxOGVjNDc4MTVjYjdkZGJiY2ZjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.b5DpN9F5TpKDOrVOfnsnlb8stRnK5oPszD2E4CHix-Q) 是不是有些错位？ @TechQuery

对比一下仓库主页的生产地址。

> 我也移除了 Bootstrap , 发现对样式没影响。

里面用了不少 Bootstrap 样式类，需要它的 CSS。

2024-10-14 15:29 UTC, luojiyin1987 commented
> > ![image](https://private-user-images.githubusercontent.com/6524977/376048721-c2becf80-f551-4c04-a790-3d160698b723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDI2NDksIm5iZiI6MTcyODkwMjM0OSwicGF0aCI6Ii82NTI0OTc3LzM3NjA0ODcyMS1jMmJlY2Y4MC1mNTUxLTRjMDQtYTc5MC0zZDE2MDY5OGI3MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMTAzOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNmYmExNWFjZWQ5NTBlMDYwYTVhMDlhMjljZDgyYTgyZDQ1ODJlOTJiMWMxOGVjNDc4MTVjYjdkZGJiY2ZjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.b5DpN9F5TpKDOrVOfnsnlb8stRnK5oPszD2E4CHix-Q) 是不是有些错位？ @TechQuery
> 
> 对比一下仓库主页的生产地址。
> 
> > 我也移除了 Bootstrap , 发现对样式没影响。
> 
> 里面用了不少 Bootstrap 样式类，需要它的 CSS。

https://fcc-cd.dev/fcc.chengdu/   ，看现在的网站， 是一样的。

2024-10-15 00:32 UTC, luojiyin1987 commented on src/pages/Index/Events/index.tsx
> +import 'swiper/css/autoplay';
css  通过 CDN 引入， 会增加维护难度。

2024-10-15 01:00 UTC, luojiyin1987 commented on src/pages/Index/Events/index.tsx
> +    }, []);
为什么优先使用 类组件？

2024-10-15 05:31 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +import 'swiper/css/autoplay';
> css  通过 CDN 引入， 会增加维护难度。

非 CSS 模块 JS 全局导入难以控制顺序，容易出现样式表优先级 bug，以致自定义样式无法覆盖原样式。

CDN 用 unpkg.com 墙内还算稳定，没啥难维护的。

2024-10-15 05:36 UTC, TechQuery requested changes

2024-10-15 05:36 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +    }
```suggestion
    private swiperRef = createRef<HTMLDivElement>();
```

2024-10-15 08:23 UTC, TechQuery requested changes
找找整个项目里哪些 CSS 可以用 Bootstrap 工具类代替。

2024-10-15 08:23 UTC, TechQuery commented on src/pages/Index/Events/index.tsx
> +                        <div className="events-slider" ref={this.swiperRef}>
```suggestion
                        <div className="events-slider">
```
除了这个初始化，其它地方完全没用上，这个变量全篇都删了吧。

2024-10-15 14:44 UTC, luojiyin1987 commented
> 找找整个项目里哪些 CSS 可以用 Bootstrap 工具类代替。

我已经尝试一次了， 应该还是有遗漏。

2024-10-15 15:46 UTC, TechQuery requested changes

2024-10-15 15:46 UTC, TechQuery commented on src/pages/Events/index.tsx
> +            <Col className="col-12">
```suggestion
            <Col xs={12}>
```

2024-10-15 15:53 UTC, TechQuery commented
> > 找找整个项目里哪些 CSS 可以用 Bootstrap 工具类代替。
> 
> 我已经尝试一次了， 应该还是有遗漏。

SCSS 文件里有很多 CSS 属性都有对应工具类，这些文件挨个看一遍，Bootstrap 工具类文档里很多都有 CSS class 可以直接写在 JSX `className` 里，能删减大量 CSS 代码。

2024-10-16 01:53 UTC, luojiyin1987 commented on src/pages/Events/index.tsx
> +            <Col className="col-12">
这个试过修改，直接替换会排版错位

2024-10-16 04:21 UTC, luojiyin1987 commented
现在是直接用 Row  Col 组件了。

2024-10-16 05:16 UTC, TechQuery commented on src/pages/Events/index.tsx
> +            <Col className="col-12">
> 这个试过修改，直接替换会排版错位

错位截图贴上来，这个属性最终就会渲染出同样的类名。

2024-10-16 05:22 UTC, TechQuery requested changes

2024-10-16 05:22 UTC, TechQuery commented on src/layouts/Footer.tsx
> +        <div className="container-fluid footer-bg">
```suggestion
        <Container fluid className="footer-bg">
```

2024-10-16 05:22 UTC, TechQuery commented on src/layouts/Footer.tsx
> +                        <img src={FLogo} alt="FCC logo" className="img-fluid" />
```suggestion
                        <Image src={FLogo} alt="FCC logo" fluid />
```

2024-10-16 05:22 UTC, TechQuery commented on src/pages/Index/Info/index.tsx
>  const info1 = new URL('../../../assets/images/info1.png', import.meta.url) + '';
```suggestion
import { Row, Col } from 'react-bootstrap';

const info1 = new URL('../../../assets/images/info1.png', import.meta.url) + '';
```

2024-10-16 05:22 UTC, TechQuery commented on src/pages/Index/Info/index.tsx
>                      <img src={require('../../../assets/images/info2.png')} />
图片导入路径采用本文件顶部那种方式。

2024-10-16 05:22 UTC, TechQuery commented on src/pages/Sponsors/index.tsx
>  import sponsors from './data';
```suggestion
import { Row, Col } from 'react-bootstrap';

import sponsors from './data';
```

2024-10-16 07:34 UTC, TechQuery approved these changes

2024-10-16 07:35 UTC, merged

2024-10-16 07:35 UTC, luojiyin1987 commented on src/pages/Events/index.tsx
> +            <Col className="col-12">
应该是我当时写错  CSS class  拼写