Feat docker compose with caddy
FreeCodeCamp-Chengdu/fcc.chengdu pull request #30
Opened 2024-10-16 15:31 UTC by luojiyin1987

Closed  #29 
因为没确定实际用的 域名和路径， Caddyfile 还没写好。
@TechQuery

2024-10-16 15:55 UTC, TechQuery requested changes

2024-10-16 15:55 UTC, TechQuery commented on .dockerignore
> +.DS_Store
此处不用改

2024-10-16 15:55 UTC, TechQuery commented on Caddyfile
没必要这么复杂吧？直接在 Docker compose 中用 Caddy 镜像一条命令拉起来行不行？

2024-10-17 05:24 UTC, TechQuery requested changes

2024-10-17 05:24 UTC, TechQuery commented on package.json
> +        "@types/swiper": "^6.0.0",
最新版内置类型，老版类型不用装了吧？

2024-10-17 05:24 UTC, TechQuery commented on docker-compose.yml
> +        container_name: fcc-chengdu
```suggestion
        image: freecodecamp-chengdu/web-site:latest
        container_name: fcc-chengdu-web
```

2024-10-17 05:24 UTC, TechQuery commented on Caddyfile
> +example.com {
```suggestion
test.fcc-cd.dev {
```

2024-10-17 05:24 UTC, TechQuery commented on .dockerignore
> -.*
开发用的隐藏文件没必要打包进去吧？

2024-10-17 05:24 UTC, TechQuery commented on Dockerfile
> +RUN pnpm run build
应该是先复制依赖配置文件来充分利用缓存，再安装、构建。

过于浅显的注释和没必要的空格也都删了吧。

2024-10-17 06:57 UTC, luojiyin1987 commented on package.json
> +        "@types/swiper": "^6.0.0",
wsl 的问题，磁盘使用率上来后， 有些文件就找不到了

2024-10-17 07:30 UTC, TechQuery requested changes

2024-10-17 07:30 UTC, TechQuery commented on Caddyfile
> +# replace example.com with your actual domain
```suggestion
```

2024-10-17 07:30 UTC, TechQuery commented on Dockerfile
> +EXPOSE 80 443
```suggestion
COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

COPY . /app
RUN pnpm build

# run HTTP server container
FROM caddy

# copy distribution files from build container
COPY --from=build /app/dist /usr/share/caddy

# expose ports
EXPOSE 80 443
```

2024-10-17 07:30 UTC, TechQuery commented on docker-compose.yml
> +                ]
```suggestion
               - 'CMD'
               - 'wget'
               - '--no-verbose'
               - '--tries=1'
               - '--spider'
               - 'http://localhost'
```
YAML 数组可以这么写

2024-10-17 07:43 UTC, luojiyin1987 commented on docker-compose.yml
> +                ]
什么意思？ 不理解
原来事   `test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]`，代码格式化后就变成现在的这样子。

2024-10-17 10:55 UTC, TechQuery commented on docker-compose.yml
> +                ]
> 什么意思？ 不理解

YAML 数组有两种形式：一种可以横着来，是 JSON 字面量；另一种用于竖着的，像 Markdown 列表一样。

> 原来事   `test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]`，代码格式化后就变成现在的这样子。

你要是还想横着的话，就去加一个配置让 YAML 按 2 空格缩进。

2024-10-17 12:45 UTC, TechQuery approved these changes

2024-10-17 12:46 UTC, merged